### ISSUE TITLE
problem installing via conda

### ISSUE THREAD

**Issue by robomotic** [rapidsai/clx#259] opened 2020-10-15 11:38 UTC
Hello,
I have a weird behaviour.
Setup: Centos7, 64bit with CUDA 11, conda.
My activate environment is called rapids37 which has already installed all the rapids packages.

I run the commandline and after a few hours.

`conda install -c rapidsai-nightly -c nvidia -c pytorch -c conda-forge -c defaults clx`
I get this:

The following specifications were found to be incompatible with your system:
```

  - feature:/linux-64::__cuda==11.1=0
  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__cuda==11.1=0
  - feature:|@/linux-64::__glibc==2.17=0
  - cugraph -> nccl[version='>=2.5'] -> __glibc[version='>=2.17']
  - cuml -> nccl[version='>=2.5'] -> __glibc[version='>=2.17']
  - cupy -> nccl=2.7.8.1 -> __glibc[version='>=2.17']
  - libcugraph -> nccl[version='>=2.5'] -> __glibc[version='>=2.17']
  - libcuml -> libfaiss=1.6.3 -> __glibc[version='>=2.17']
  - libfaiss -> __glibc[version='>=2.17']
  - libxgboost -> nccl[version='>=2.5'] -> __glibc[version='>=2.17']
  - nccl -> __glibc[version='>=2.17']
  - rapids -> nccl[version='>=2.7.8.1,<3.0a0'] -> __glibc[version='>=2.17']
  - rapids-xgboost -> nccl[version='>=2.7.8.1,<3.0a0'] -> __glibc[version='>=2.17']
  - ucx -> __glibc[version='>=2.17,<3.0.a0']
  - ucx-py -> ucx==1.8.1+g6b29558 -> __glibc[version='>=2.17,<3.0.a0']
  - xgboost -> nccl[version='>=2.7.8.1,<3.0a0'] -> __glibc[version='>=2.17']
```
`
Your installed version is: 2.17`

Seems all good, but then the module is not installed (module import not found) and I can't even find it in conda lista.

```
(rapids37) [jupyter@c109518 ~]$ python
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import clx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'clx'
>>> 

```

Any help appreciated!

**Comment by BartleyR** [comment] 2020-10-15 15:15
It looks like you're trying to use CUDA 11.1, which we don't currently support due to our dependency on PyTorch. There is an internal team at Facebook working on addressing this, and you can follow our similar GH issue here: https://github.com/rapidsai/ops/issues/1095#issuecomment-673601718.

For the time being, we'd advise using a CUDA version that's compatible with PyTorch (CUDA 10.2 is a great choice) if possible. You can have multiple CUDA versions installed on your system, if that's an option for you. Another option is to use our Docker container, which runs CUDA 10.2 inside but will work fine with the CUDA 11.0 toolkit on your bare metal (assuming you have a [supported driver](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#cuda-application-compatibility), which is very likely).

**Comment by BartleyR** [comment] 2020-10-21 18:50
@robomotic did you have an opportunity to test this at all?

**Comment by robomotic** [comment] 2020-10-25 09:10
Ops sorry my GPU server got torched, I have to reconfigure it. Please feel free to close the issue and I will re-open if it doesn't work from a fresh install.

**Comment by robomotic** [comment] 2020-11-25 16:02
Testing now!

**Comment by robomotic** [comment] 2020-11-25 16:30
Okay this is what I did:

```
docker pull rapidsai/rapidsai:cuda10.2-runtime-ubuntu18.04-py3.8
docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786  rapidsai/rapidsai:cuda10.2-runtime-ubuntu18.04-py3.8
```

Host Environment:

Ubuntu 20.04 x64 
Cuda 11.0
Nvidia-Toolkit

Kernel driver:

alias:          char-major-195-*
version:        455.38
supported:      external
license:        NVIDIA
srcversion:     3069C056DC628FE163D2CF4
name:           nvidia
vermagic:       5.4.0-54-generic SMP mod_unload 

I then try to import clx and I get the module not found error.
Let me know if there is something else I can try.

**Comment by efajardo-nv** [comment] 2020-11-30 15:56
@robomotic Looks like the issue is that you're conda installing the nightly conda package (0.17) on the stable rapidsai docker image (0.16). Could you try this to install on `rapidsai/rapidsai:cuda10.2-runtime-ubuntu18.04-py3.8`:

`conda install -c rapidsai -c nvidia -c pytorch -c conda-forge -c defaults clx`

If you want to use the very latest, you would use the nightly rapidsai image and nightly clx conda package:
```
docker pull rapidsai/rapidsai-nightly:cuda10.2-runtime-ubuntu18.04-py3.8
conda install -c rapidsai-nightly -c nvidia -c pytorch -c conda-forge -c defaults clx
```

**Comment by BartleyR** [comment] 2020-12-14 17:00
@robomotic Is this working for you now?

**Comment by robomotic** [comment] 2020-12-14 21:19
Hi!
Thanks for the update I am going to test it shortly.
Cheers.

**Comment by priamai** [comment] 2020-12-15 22:44
Holy moly guacamole, that worked pretty well.
Please add this in the tutorial or documentation, it will be helpful for other people.
Cheers!

**Comment by efajardo-nv** [comment] 2021-02-10 16:54
Closing this. Please create new issue if problem still persists.

**Closed by efajardo-nv** 2021-02-10 16:54 UTC
Labels: 4 - Waiting on Author, question
